stages:
    - build
    - test

build:
    stage: build
    script:
        - echo "Build du projet"
        - mvn clean
test:
    stage: test
    script:
        - echo "Vérification si les tests actifs passent"
        - mvn test
